export { default as Navbar } from './Navbar'
export { default as Cryptocurrencies } from './Cryptocurrencies'
export { default as CryptoDetails } from './CryptoDetails'
export { default as Homepage} from './Homepage'
export { default as News } from './News'
export { default as PopularMovies } from './PopularMovies'
export { default as Movies } from './Movies'
export { default as TopMovies } from './TopMovies'
export { default as SearchMovies} from './SearchMovies'
export { default as SearchActors} from './SearchActors'